### ISSUE TITLE
Ops Matcher yields incomplete/insufficient error data

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#25]
As of now I find that the Ops matcher hides/conceals too much error information when it determines that no match can be made. See, for example, [here](**https://github.com/scijava/scijava-ops/blob/b7fdd065d521f6b812a5cf1e6d35ce748407572a/src/main/java/org/scijava/ops/transform/DefaultOpTransformerService.java#L94**), where the Op Matcher completely disregards the `OpMatchingException`.

This is less of a question of dumping out all of the information but more about being smarter about what we dump out. For example, we will be traversing the code linked above many times, and most of those times we will be attempting a transformation for which there will be no matching Op. This is what the `OpMatchingException` will say. Of course we (probably?) do not want printouts for each attempted transformation due to the sheer amount of attempts that might happen. However we might have great interest in an `OpMatchingException` stating that there are two allowable matches. This is something that, unless one debugs the code, might be easily overlooked because this information is automatically ignored.

In this way a discussion might be in order as to what information should be printed out.

**Comment by gselzer** [comment]
Since I did not have the time yesterday, here is an example of what I am attempting to describe. This code was written for `QuickHull3DTest`:
```java
		Mesh df = randomPoints(100000, 20150818);

		final List<?> result = (List<?>) ops.run("geom.convexHull", df);
```
For this test, the matcher is not able to provide an `Op` for `ops.run()` to run. Here is the output given as to why it was not able to provide an `Op`:
```
java.lang.IllegalArgumentException: org.scijava.ops.matcher.OpMatchingException: No matching 'geom.convexHull/org.scijava.ops.transform.OpRunner' op

Request:
-	Name: "geom.convexHull", Types: [interface org.scijava.ops.transform.OpRunner]
Input Types: 
		* net.imagej.mesh.naive.NaiveDoubleMesh
Output Type: 
		* Any

Candidates:
-	 No candidates found!
	at org.scijava.ops.OpService.findOpInstance(OpService.java:383)
	at org.scijava.ops.OpService.findOpInstance(OpService.java:362)
	at org.scijava.ops.OpService.run(OpService.java:422)
	at net.imagej.ops.geom.QuickHull3DTest.quickhull_40_Test(QuickHull3DTest.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.scijava.ops.matcher.OpMatchingException: No matching 'geom.convexHull/org.scijava.ops.transform.OpRunner' op

Request:
-	Name: "geom.convexHull", Types: [interface org.scijava.ops.transform.OpRunner]
Input Types: 
		* net.imagej.mesh.naive.NaiveDoubleMesh
Output Type: 
		* Any

Candidates:
-	 No candidates found!
	at org.scijava.ops.matcher.MatchingResult.singleMatch(MatchingResult.java:60)
	at org.scijava.ops.matcher.DefaultOpTypeMatchingService.findSingleMatch(DefaultOpTypeMatchingService.java:71)
	at org.scijava.ops.OpService.findOpInstance(OpService.java:371)
	... 28 more
```
Now, if I debug the matching process and find the point at which the matcher is looking for a `Function` to satisfy the Function -> OpRunner transformation that I want, I get the following `OpMatchingException`:
```
org.scijava.ops.matcher.OpMatchingException: Multiple 'geom.convexHull/java.util.function.Function<net.imagej.mesh.naive.NaiveDoubleMesh, Any>' ops of priority 0.0:
Incomplete output type checking may have occured!
1. net.imagej.ops.geom.geom3d.DefaultConvexHull3D(
	 Inputs:
		net.imagej.mesh.Mesh input
	 Outputs:
		net.imagej.mesh.Mesh convexHull
)

2. net.imagej.ops.geom.geom3d.DefaultConvexHull3DEpsilon(
	 Inputs:
		net.imagej.mesh.Mesh input
	 Outputs:
		java.lang.Double epsilon
)


Request:
-	Name: "geom.convexHull", Types: [java.util.function.Function<net.imagej.mesh.naive.NaiveDoubleMesh, Any>]
Input Types: 
		* net.imagej.mesh.naive.NaiveDoubleMesh
Output Type: 
		* Any

Candidates:
1. 	(net.imagej.mesh.Mesh convexHull) =
	net.imagej.ops.geom.geom3d.DefaultConvexHull3D(
		net.imagej.mesh.Mesh input)
	MATCH
2. 	(java.lang.Double epsilon) =
	net.imagej.ops.geom.geom3d.DefaultConvexHull3DEpsilon(
		net.imagej.mesh.Mesh input)
	MATCH
```
Ah, so it is not that the matcher was not able to find a satisfying `Op`, it was instead that there were two different `Op`s that matched equally, thus allowing no output. But seeing as this information is not given in the final output that is given due to the failing test, there is no way to know what actually happened without taking this time to dig in.

On a similar note, it might also be very helpful to record, for every `Op` that has a matching name and rawtype to that which was asked for, what did not match, which would help the user greatly in determining which of their parameters is/are preventing a match with that particular `Op`. Of course, this output *could* potentially get very long, so we would have to be smart in implementing this, however I would argue that too much information is better than none, and as someone who writes a lot of tests that need a lot of `Type` massaging, this would save a lot of time in identifying the issue at hand.

**Comment by gselzer** [comment]
Another such situation in which the error logging is insufficient is when a `OpDependency` also has an `OpDependency` and that nested `OpDependency` is the one that cannot match. For example, I am currently porting `DeconvolveTest`. When I call 
```
final Img<FloatType> convolved = (Img<FloatType>) ops.run(
			"filter.convolve", incropped, kernel, context.getService(ThreadService.class).getExecutorService());
```
, with the intent of matching the `Op` class `SimpleConvolveFFTF`, I get the error message
```
java.lang.IllegalArgumentException: Execution of Op transformatioon failed:
org.scijava.ops.matcher.OpMatchingException: Could not find Op that matches requested Op dependency:
Op class: net.imagej.ops.filter.convolve.SimpleConvolveFFTF
Dependency identifier: convolveOp

 Attempted request:
Name: "filter.convolve", Types: [org.scijava.ops.core.function.Function7<net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>, net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>, [J, net.imglib2.outofbounds.OutOfBoundsFactory<net.imglib2.type.numeric.real.FloatType, net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>>, net.imglib2.type.numeric.real.FloatType, net.imglib2.type.numeric.complex.ComplexFloatType, java.util.concurrent.ExecutorService, net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>>]
Input Types: 
		* net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>
		* net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>
		* long[]
		* net.imglib2.outofbounds.OutOfBoundsFactory<net.imglib2.type.numeric.real.FloatType, net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>>
		* net.imglib2.type.numeric.real.FloatType
		* net.imglib2.type.numeric.complex.ComplexFloatType
		* java.util.concurrent.ExecutorService
```
Upon debugging and viewing the `OpDependency` resolution, I see that the issue is actually upon resolving the correct `filter.padShiftFFTKernel` `Op`:
```
org.scijava.ops.matcher.OpMatchingException: Multiple 'filter.padShiftFFTKernel/java.util.function.BiFunction<net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>, net.imglib2.Dimensions, net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>>' ops of priority 100.0:
Incomplete output type checking may have occured!
1. net.imagej.ops.filter.pad.DefaultPadShiftKernelFFT(
	 Inputs:
		I input
		net.imglib2.Dimensions paddedDimensions
	 Outputs:
		O output
)

2. net.imagej.ops.filter.pad.PadShiftKernelFFTMethods(
	 Inputs:
		I input
		net.imglib2.Dimensions paddedDimensions
	 Outputs:
		O output
)


Request:
-	Name: "filter.padShiftFFTKernel", Types: [java.util.function.BiFunction<net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>, net.imglib2.Dimensions, net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>>]
Input Types: 
		* net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>
		* net.imglib2.Dimensions
Output Type: 
		* net.imglib2.RandomAccessibleInterval<net.imglib2.type.numeric.real.FloatType>

Candidates:
1. 	(O output) =
	net.imagej.ops.filter.pad.DefaultPadShiftKernelFFT(
		I input,
		net.imglib2.Dimensions paddedDimensions)
	MATCH
2. 	(O output) =
	net.imagej.ops.filter.pad.PadShiftKernelFFTMethods(
		I input,
		net.imglib2.Dimensions paddedDimensions)
	MATCH
```

There is absolutely no way to know that this was the problem with the dependency resolution from the message given above.

**Comment by gselzer** [comment]
Another item to add to the wish list: when a particular Op with a matching name fails, explicitly explain why:
* If it is due to the Op's raw type, log that it was due to a raw type mismatch (i.e. BiFunction cannot be run as a Function3). This might be a little complicated due to transformations, however arities should be easy enough.
* If it is due to a difference in type parameters, log which set of type parameters is incongruent **with the index**

**Comment by gselzer** [comment]
Time commitment: 1 week

**Comment by hinerm** [comment]
Some test cases and feedback:
Is there a test for how errors are handled/reported within an `OpEnvironment`? I only see positive tests in [OpEnvironmentTest](https://github.com/scijava/incubator/blob/ffc89fa6990112a33ba23277984555e08c3837e7/scijava/scijava-ops-engine/src/test/java/org/scijava/ops/engine/OpEnvironmentTest.java)

I played around with the `OpMethodDependencyPositionTest`:
```java
	public static class GoodOpCollection implements OpCollection {
		@OpMethod(names="good", type=Computers.Arity1.class)
		public static void goodDep( //
				@OpDependency(name = "someDep") Function<String, Long> op, //
				List<String> in, //
				List<Long> out //
		)
		{
			out.clear();
			for (String s : in)
				out.add(op.apply(s));
		}
	}

	public static class BadOpCollection implements OpCollection {
		@OpMethod(names = "bad", type = Computers.Arity1.class)
		public static void badDep( //
				List<String> in, //
				@OpDependency(name = "someDep") Function<String, Long> op, //
				List<Long> out //
		)
		{
			out.clear();
			for (String s : in)
				out.add(op.apply(s));
		}
	}

	@Test
	public void testOpDependencyAfter() throws NoSuchMethodException {
		ops.register(new BadOpCollection());
	}
```

It feels strange to me that this test passes and I have to actually attempt an op match attempt to get an exception:

```java
ops.op("bad").arity1().inType(new Nil<List<String>>(){}).outType(new Nil<List<Long>>(){}).computer();
```

Then I noticed that this also fails if we register the "good" `OpCollection`, because neither of these ops are actually _valid_ since their dependencies don't exist. Dependency validity should be tested separately, and not mingled with positional testing. Does that test already exist?

So then I was curious what happens when there are bad ops but we try to use good ones, so I do:
```java
		ops.register(new BadOpCollection());
		ops.register(new GoodOpCollection());
		ops.register(new MathOpCollection());
		ops.op("math.add").arity2().inType(Number.class,Number.class).outType(Double.class).function();
```

This produces an error message about the "bad" op... but why doesn't it produce on for the "good" op with the invalid dependency? I don't see a way to get hold of that error message since no exception is thrown; programmatically there's no indication anything has gone wrong.

Which then leads to the question: if I'm matching a valid Op why would I even care about unrelated, invalid Ops?

**Comment by gselzer** [comment]
> It feels strange to me that this test passes and I have to actually attempt an op match attempt to get an exception:

Yeah, that's because `OpInfo` generation (and thus validity checking) happens lazily - namely, when you first try to match an Op. I do agree that it feels strange, and have thought about trying to resort to more eager `OpInfo` generation.

> Dependency validity should be tested separately, and not mingled with positional testing. Does that test already exist?

@hinerm what do you mean by "dependency validity"? Do you mean "whether a dependency exists in the environment"?

If so, we don't test that because it's *super* difficult to validate dependency validity, as different dependencies may be matched based on different inputs. Consider the [`MeanFunction`](https://github.com/scijava/incubator/blob/6ac889150f9911bf6fd02a2d87de8af22dd50750/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/stats/Mean.java#L12), which enables computing means on any types for which summation, counting, and division are defined

> This produces an error message about the "bad" op... but why doesn't it produce on for the "good" op with the invalid dependency? I don't see a way to get hold of that error message since no exception is thrown; programmatically there's no indication anything has gone wrong.

Well, I'd argue that nothing *has* gone wrong - a dependency's "validity" depends entirely on the context of your search.

> Which then leads to the question: if I'm matching a valid Op why would I even care about unrelated, invalid Ops?

I'm not sure you should, however the framework is not suited towards reporting that, especially now that we're moving towards throwing errors in scijava/incubator#88. I still think that change is good, but I'd prefer that the errors instead get logged - we'll have to solve scijava/incubator #82 though...

**Comment by hinerm** [comment]
>Well, I'd argue that nothing has gone wrong - a dependency's "validity" depends entirely on the context of your search.
>I'm not sure you should, however the framework is not suited towards reporting that, especially now that we're moving towards throwing errors

@gselzer to be clear, I agree that nothing has gone wrong in the context of the search. My point was that, despite the search being fine, Ops _does_ report _some_ errors (for the "bad" op collection), but not others (the "good" op collection). Does that make sense?

Maybe this is all solved in https://github.com/scijava/incubator/pull/88 I just want to make sure we're all in agreement that when executing Ops is not the right time to be presenting error messages about the (in)validity of unrelated Ops.

>@hinerm what do you mean by "dependency validity"? Do you mean "whether a dependency exists in the environment"?

Yes, I meant that there should be a test that demonstrates the expected behavior when an Op is written with an OpDependency that cannot be satisfied. Presumably, through catching an exception in https://github.com/scijava/incubator/pull/88

**Comment by gselzer** [comment]
> My point was that, despite the search being fine, Ops _does_ report _some_ errors (for the "bad" op collection), but not others (the "good" op collection). Does that make sense?

Sorry, @hinerm, I still don't understand. What is the error that you expect to see for the good Op collection?

> Maybe this is all solved in [scijava/incubator#88](https://github.com/scijava/incubator/pull/88) I just want to make sure we're all in agreement that when executing Ops is not the right time to be presenting error messages about the (in)validity of unrelated Ops.

Yup, definitely in agreement there.

> Yes, I meant that there should be a test that demonstrates the expected behavior when an Op is written with an OpDependency that cannot be satisfied. Presumably, through catching an exception in https://github.com/scijava/incubator/pull/88

Well, like I said, we can't know that until runtime, so we *have* to catch that at matching time.

**Comment by hinerm** [comment]
> Sorry, @hinerm, I still don't understand. What is the error that you expect to see for the good Op collection?

The `goodDep` Op has its `OpDependency` listed in the correct order, but the requested `"someDep"` op _does not exist_. So the `goodDep` Op is actually invalid.. so I'd expect to see an error to that effect.

>Well, like I said, we can't know that until runtime, so we have to catch that at matching time.

That's fine. I think: a) the `goodDep` op should have a _valid_ `OpDependency`, and b) there should be a test for an op like the current `goodDep` that has `OpDependency` in the correct leading position, but refers to an invalid Op, that should then try to use that Op and ensure that an appropriate error of the missing dependency is reported.

**Comment by ctrueden** [comment]
#134 provides an illustration of a matching failure with the current codebase.

**Comment by hinerm** [comment]
Here is an example of a current `ValidityException` being thrown. It should give some indication *which* op was invalid

```
java.lang.IllegalArgumentException: java.lang.RuntimeException: org.scijava.common3.validity.ValidityException: * java.lang.IllegalArgumentException: Op Dependencies in static methods must come before any other parameters!
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.parse(YAMLOpInfoDiscoverer.java:94)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.lambda$discover$0(YAMLOpInfoDiscoverer.java:47)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.discover(YAMLOpInfoDiscoverer.java:45)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.lambda$initOpDirectory$12(DefaultOpEnvironment.java:703)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.initOpDirectory(DefaultOpEnvironment.java:703)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.infos(DefaultOpEnvironment.java:178)
	at net.imagej.ops2@0-SNAPSHOT/net.imagej.ops2.OpRegressionTest.opDiscoveryRegressionIT(OpRegressionTest.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: org.scijava.common3.validity.ValidityException: * java.lang.IllegalArgumentException: Op Dependencies in static methods must come before any other parameters!

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.AbstractYAMLOpInfoCreator.create(AbstractYAMLOpInfoCreator.java:42)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.parse(YAMLOpInfoDiscoverer.java:88)
	... 85 more
Caused by: org.scijava.common3.validity.ValidityException: * java.lang.IllegalArgumentException: Op Dependencies in static methods must come before any other parameters!

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpMethodInfo.<init>(OpMethodInfo.java:103)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpMethodInfo.<init>(OpMethodInfo.java:82)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.JavaMethodYAMLInfoCreator.create(JavaMethodYAMLInfoCreator.java:61)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.AbstractYAMLOpInfoCreator.create(AbstractYAMLOpInfoCreator.java:40)
	... 86 more


java.lang.IllegalArgumentException: java.lang.RuntimeException: org.scijava.common3.validity.ValidityException: * java.lang.IllegalArgumentException: Op Dependencies in static methods must come before any other parameters!


	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.parse(YAMLOpInfoDiscoverer.java:94)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.lambda$discover$0(YAMLOpInfoDiscoverer.java:47)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.discover(YAMLOpInfoDiscoverer.java:45)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.lambda$initOpDirectory$12(DefaultOpEnvironment.java:703)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.initOpDirectory(DefaultOpEnvironment.java:703)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.infos(DefaultOpEnvironment.java:178)
	at net.imagej.ops2@0-SNAPSHOT/net.imagej.ops2.OpRegressionTest.opDescriptionRegressionIT(OpRegressionTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: org.scijava.common3.validity.ValidityException: * java.lang.IllegalArgumentException: Op Dependencies in static methods must come before any other parameters!

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.AbstractYAMLOpInfoCreator.create(AbstractYAMLOpInfoCreator.java:42)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.YAMLOpInfoDiscoverer.parse(YAMLOpInfoDiscoverer.java:88)
	... 85 more
Caused by: org.scijava.common3.validity.ValidityException: * java.lang.IllegalArgumentException: Op Dependencies in static methods must come before any other parameters!

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpMethodInfo.<init>(OpMethodInfo.java:103)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpMethodInfo.<init>(OpMethodInfo.java:82)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.JavaMethodYAMLInfoCreator.create(JavaMethodYAMLInfoCreator.java:61)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.yaml.AbstractYAMLOpInfoCreator.create(AbstractYAMLOpInfoCreator.java:40)
	... 86 more
```

**Comment by hinerm** [comment]
Another example, if you duplicate some Ops like by renaming [the templates](https://github.com/scijava/incubator/tree/main/imagej/imagej-ops2/templates/main/java/net/imagej/ops2/adapt) without deleting the old templates, then run a test that requires these ops, they will fail with no candidate found. However there was never any indication of the collision.

```
org.scijava.ops.api.features.OpMatchingException: No MatchingRoutine was able to produce a match!

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.agglomeratedException(DefaultOpMatcher.java:80)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:74)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.findOpCandidate(DefaultOpEnvironment.java:472)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.generateCacheHit(DefaultOpEnvironment.java:449)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.findOp(DefaultOpEnvironment.java:383)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.impl.DefaultOpEnvironment.op(DefaultOpEnvironment.java:238)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpBuilder.matchFunctionHelper(OpBuilder.java:14572)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpBuilder.matchFunction(OpBuilder.java:14422)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpBuilder$Arity2_IV_OT.function(OpBuilder.java:1588)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpBuilder$Arity2_IV_OT.apply(OpBuilder.java:1616)
	at net.imagej.ops2@0-SNAPSHOT/net.imagej.ops2.math.ImageBinaryMathTest.addImageF(ImageBinaryMathTest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	Suppressed: org.scijava.ops.api.features.OpMatchingException: No matching 'math.add/java.util.function.BiFunction<net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.Img<net.imglib2.type.numeric.integer.IntType>>' op

Request:
-	Name: "math.add", Types: java.util.function.BiFunction<net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.Img<net.imglib2.type.numeric.integer.IntType>>
Input Types: 
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>
Output Type: 
		* net.imglib2.img.Img<net.imglib2.type.numeric.integer.IntType>

Candidates:
-	 No candidates found!
		at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.features.MatchingResult.singleMatch(MatchingResult.java:67)
		at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:60)
		at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 79 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: Unable to find an Op adaptation for org.scijava.ops.api.features.MatchingConditions@4f34fce2
		at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.adapt.AdaptationMatchingRoutine.findMatch(AdaptationMatchingRoutine.java:162)
		at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 79 more
	Suppressed: org.scijava.ops.api.features.OpMatchingException: No matching 'math.add/java.util.function.BiFunction<net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.Img<net.imglib2.type.numeric.integer.IntType>>' op

Request:
-	Name: "math.add", Types: java.util.function.BiFunction<net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>, net.imglib2.img.Img<net.imglib2.type.numeric.integer.IntType>>
Input Types: 
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>
		* net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.IntType, net.imglib2.img.basictypeaccess.array.IntArray>
Output Type: 
		* net.imglib2.img.Img<net.imglib2.type.numeric.integer.IntType>

Candidates:
-	 No candidates found!
		at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.features.MatchingResult.singleMatch(MatchingResult.java:67)
		at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.RuntimeSafeMatchingRoutine.findMatch(RuntimeSafeMatchingRoutine.java:60)
		at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.features.MatchingRoutine.match(MatchingRoutine.java:43)
		at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.DefaultOpMatcher.match(DefaultOpMatcher.java:66)
		... 79 more
```

**Comment by hinerm** [comment]
So in exploring why one of my ops wasn't being matched, I found that a very helpful exception **is thrown** and recorded [here](https://github.com/scijava/incubator/blob/753836daaa7960d42003bf43b19db76809a77a2f/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/matcher/impl/DefaultOpMatcher.java#L69)... however it's for the failure of a very particular Op (in this case an adaptor) and was one of several adaptors that failed to match, from the [adaptation matching routine](https://github.com/scijava/incubator/blob/753836daaa7960d42003bf43b19db76809a77a2f/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/matcher/adapt/AdaptationMatchingRoutine.java#L99-L100)... which is caught and then [**totally discarded**](https://github.com/scijava/incubator/blob/753836daaa7960d42003bf43b19db76809a77a2f/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/matcher/adapt/AdaptationMatchingRoutine.java#L154).

This information should be preserved and added to the overall agglomerated exception. It would be wonderful to have a tree of exceptions showing the different matches that were attempted and how each failed. It seems we have that info it's just not fully connected.

**Comment by hinerm** [comment]
So I think the original problem here is currently resolved as long as you are not using adaptation. Prior to a commit I will discuss below, if I create duplicate [subtract ops](https://github.com/scijava/incubator/blob/2917457c5fa549c95f0966b4913a13e318c3c227/imagej/imagej-ops2/src/main/java/net/imagej/ops2/math/BinaryNumericTypeMath.java#L100-L112) and [test them as computers](https://github.com/scijava/incubator/blob/2917457c5fa549c95f0966b4913a13e318c3c227/imagej/imagej-ops2/src/test/java/net/imagej/ops2/math/BinaryNumericTypeMathTest.java#L63-L67) then I will get an error, the top of which shows:

```
	Suppressed: org.scijava.ops.api.OpMatchingException: Multiple 'math.sub/org.scijava.function.Computers.Arity2<net.imglib2.type.numeric.integer.IntType, net.imglib2.type.numeric.integer.IntType, net.imglib2.type.numeric.integer.IntType>' ops of priority 100.0:
1. math.sub(
	 Inputs:
		T null
		T null
	 Containers (I/O):
		T container1
)
Aliases: [math.subtract]

2. math.sub(
	 Inputs:
		T null
		T null
	 Containers (I/O):
		T container1
)
Aliases: [math.subtract]
```

But if I test _as a function_ (requiring adaptation) the exception would be:
```
	Suppressed: org.scijava.ops.api.OpMatchingException: No matching 'math.sub/java.util.function.BiFunction<net.imglib2.type.numeric.integer.IntType, net.imglib2.type.numeric.integer.IntType, net.imglib2.type.numeric.integer.IntType>' op

Request:
-	Name: "math.sub", Types: java.util.function.BiFunction<net.imglib2.type.numeric.integer.IntType, net.imglib2.type.numeric.integer.IntType, net.imglib2.type.numeric.integer.IntType>
Input Types: 
		* net.imglib2.type.numeric.integer.IntType
		* net.imglib2.type.numeric.integer.IntType
Output Type: 
		* net.imglib2.type.numeric.integer.IntType
```

So the commit I made to try and improve this was https://github.com/scijava/incubator/commit/94d8366d227405c6026cfb96b949e10613f6cdf9, which **does indeed** then include the suppressed `Multiple math.sub...` exceptions... but it's kind of buried in 400 lines of exception messages. Which doesn't sound _so_ terrible until you test it with a [complex adaptation](https://github.com/scijava/incubator/blob/2917457c5fa549c95f0966b4913a13e318c3c227/imagej/imagej-ops2/src/test/java/net/imagej/ops2/math/ImageBinaryMathTest.java#L79-L86) and it balloons to 2k lines. 😢  The multiple subtractions is on line `819` and there are 7 other "multiple op" failure messages (all superfluous).

I am inclined to just leave the commit because at least we have the info and someone familiar with Ops could potentially parse it, while leaving pruning of the fluff exceptions for paper 2+. Any objections @ctrueden @gselzer?

**Comment by hinerm** [comment]
As I believe we are now capturing _all_ error data, verbose as it may be, I'm going to close this
